services:
  odl_hybrid:
    build:
      context: ./backend
      dockerfile: Dockerfile.odl
    container_name: odl_hybrid_container
    restart: unless-stopped
    working_dir: /app
    volumes: []
    environment:
      - TZ=UTC
    gpus: all
